### ISSUE TITLE
More emag features and/or traps

### ISSUE THREAD

**Issue by CODEMAN8926** [PelideAchille/Monkey-Station#10]
The traitor as a whole does not include many ways to trick the crew into dying, I hope for more emag features or at least some way to make items do damage to the user (I.E. an emagged door won't enable the bolts or make it completely open, it will make it constantly open and close. Or possibly using a screwdriver on a flash will make it so that it will instead flash the user when used.)

**Comment by xTheLifex** [comment]
Shouldn't each new feature be separated into multiple issues? The screwdriver on flash being a issue, and the emagged door being another one.
Or you could start making a tasklist of these features, which you can add pressing the ![image](https://user-images.githubusercontent.com/24512655/81172879-7b40a080-8f75-11ea-90f4-744dc9bc78a1.png) button when editing your issue.
