### ISSUE TITLE
Tutorials!

### ISSUE THREAD

**Issue by Darkpixel797** [PelideAchille/Monkey-Station#12]
As someone who is learning the game, I rely heavily on the tgstation wiki to function, while most of the time it serves me fine, monkeystation uses modified beestation code, which is different. Some better information about the mechanics inside or outside of the game would be very nice.

**Comment by xTheLifex** [comment]
Hello @Darkpixel797. Monkey Station's modification just got started, therefore it's still alot close to Beestation. Our documentation will eventually be made as we improve on the code. Until then, you can use [Beestation's Guide](https://wiki.beestation13.com/view/Starter_guide).

**Comment by TheRealUnabomber** [comment]
Hello @Darkpixel797, 

Thanks for asking, I think this can be done, also for the moment we can just redirect people to the Bee Wiki and for our changes I can make a new discord channel where we will explain each new issue.
