### ISSUE TITLE
Dna-keyed airlock electronics

### ISSUE THREAD

**Issue by MACIEKBAKI** [PelideAchille/Monkey-Station#13]
What it says on the tin. AIrlock electronics but keyed with DNA instead of access.

The basic idea is, as you read, airlock electronics that open only for one person with specific DNA - kind of like how the mech DNA lock works, or the DNA-keyed firing pin. 

Should silicons be able to open them? Probably.

Should you be able to reset the DNA imprinted on it? Well, yeah, but only if the DNA imprinted is your DNA. That is to say the clown can't clear the DNA on the captain's airlock DNA electronics, but the captain himself can.

**Comment by TheRealUnabomber** [comment]
Nice feature, for me is ok... it won't be that easy to code but we can try
