### ISSUE TITLE
Maint Bug

### ISSUE THREAD

**Issue by basedhamster** [PelideAchille/Monkey-Station#14]
Lower maintenance has no pressure or o2. Mainly in engi maint.

**Comment by Amompharetos** [comment]
What map is it on?

**Comment by basedhamster** [comment]
@TheRealUnabomber boxstation

**Comment by basedhamster** [comment]
@Amompharetos Boxstation

**Comment by xTheLifex** [comment]
Please provide a picture

**Comment by TheRealUnabomber** [comment]
Hello, I think he's referring to the south maint, near engineering

**Comment by basedhamster** [comment]
![image](https://user-images.githubusercontent.com/64750659/81436270-32d0e080-9137-11ea-8669-01102a0cbd34.png)

**Comment by basedhamster** [comment]
it goes all the way down to engi maint
