### ISSUE TITLE
Brain-centered slimeperson bodyswap

### ISSUE THREAD

**Issue by MACIEKBAKI** [PelideAchille/Monkey-Station#15]
## The feature: Make slimeperson bodyswap work based on your brain, not on your body - see explanation
How the slimeperson bodyswap currently works is that it's somewhat tied to bodies (havent actually checked code dont quote me on this), so if you take the brain of a slimeperson, put it in another slimeperson's cloned body (I.e. bill's brain into bob's split body) then clone it, they can access all the bodies of the person that of which the corpse they inhabit:
Bill (slimeperson) - Bodies: Bill
Bob (slimeperson) - Bodies: bob1, bob2, bob3
Kill bill, kill bob3, put Bill's brain in bob3's body, clone him.
Bill revives in bob3's body; can swap to bob2 or bob1 if it's not occupied by another mind.
If you made this brain-centerred, that could not happen - bill in bob3 couldn't swap into bob2, but if bob3's brain was instead put in an MMI or a borg shell, maybe Bob could swap into it? It could be interesting and a bit gimmicky, but might be too powergamey.
Good idea, bad idea?
To balance you can, for example, make it cost more to replicate a body - instead of 100% blood (i.e. you need 200% to replicate), make it 200% blood (300% needed in system to replicate), or something like that. 

## Why should we add it?
It could make playing slimepeople a bit more interesting, opening up more possibilities for gimmicks.

**Comment by CODEMAN8926** [comment]
Finally, a good PR.

**Comment by MACIEKBAKI** [comment]
> 
> 
> Finally, a good PR.

Note, this is not a PR, this is an idea.

additionally for balancing it you COULD have split body *NOT* actually split you a new body but just create a new brain for you to us
