### ISSUE TITLE
Make flashes great again

### ISSUE THREAD

**Issue by basedhamster** [PelideAchille/Monkey-Station#9]
Old flashes used to only blind you. Now they also make you run into walls, which is a feature I don't like. I was hoping we could change it back so that it only blinds you.

**Comment by MACIEKBAKI** [comment]
just get sunglasses

**Comment by MACIEKBAKI** [comment]
also, are you reffering to flash AOE or directed attack?

**Comment by basedhamster** [comment]
AOE
